### PR TITLE
Solarized Dark theme

### PR DESCRIPTION
**Pull request by jfdhuiz**
A port of the solarized_dark theme of powerline-shell

https://github.com/b-ryan/powerline-shell/blob/master/powerline_shell/themes/solarized_dark.py

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Please see the questions on the merge request [for the gruvbox theme](https://gitlab.com/jD91mZM2/powerline-rs/-/merge_requests/5) - specifically, how do you imagine someone would be able to use this theme?

**Comment by jfdhuiz** [comment]
I was used the mentioned Python software powerline_shell before. I switched to this one, was glad it worked with Fish and Bash and the features overal, but the default theme did not fit my use case. So I ported this theme over.

I suppose when someone uses powerline-rs, they might prefer one theme or another. If you ship these themes with the default package, people can try them right away, and you save them the hassle of having to port it themselves or having to figure out themselves.

**Comment by jD91mZM2** [comment]
Good point, so you mean just bundling this with the source is enough?

**Comment by jfdhuiz** [comment]
A more active approach wouldn't heard ie. you could mention the existence of themes in README.md. You could also mention the themes themselves ie. there is a solarized_dark and gruvbox theme here is how to enable them (IIRC --help told me too).

**Comment by jD91mZM2** [comment]
Could you change your PR to include a README update (and perhaps move the theme to a subdirectory), then? Thanks!

**Comment by jfdhuiz** [comment]
Done!

**Comment by jD91mZM2** [comment]
Cool, thanks!

**Pull request merged**
